AllCops:
  TargetRubyVersion: 2.3

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 128
  IgnoreCopDirectives: true
