AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 128
  IgnoreCopDirectives: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*
